### ISSUE TITLE
Find Weather

### ISSUE THREAD

**Issue by aaron-G18** [benjamintownsend02/groupProj1#4]
## User Story

As a user, I want to be able to find out what the weather (10 day) will be like in a city I want to travel to, so that I know how to pack.

## Acceptance Criteria
- [x] index.html has a text input so they can search the city.
- [x] index.html has a search button for event handler(s).
- [x] javascript has AJAX function to create query URL for weather API.
- [x] javascript has function to return weather info from API and update the html.

**Comment by VIII4** [comment]
Complete. Phase II will be added to issues...(make information visually appealing in application)
